### ISSUE TITLE
Questions about this fork

### ISSUE THREAD

**Issue by GeitHub** [SuperrSonic/RA-SS#1]
I'm curious as to how you're implementing this fork of RA (are you using it as a backend for an HDD/SD Loader like Wiiflow? Or are you only using it for a handful of games and using channel forwarders to get into RA?). I'm also wondering if there's a way you can easily merge/build your commits with updated revisions to the master RA as they're released (sorry, I'm new to Github). Thanks & great work.

**Comment by SuperrSonic** [comment]
It can be used for Wiiflow, but I personally prefer making a VC-like banner with a forwarder that loads the dol with the game path and give it a specific set of settings. Thing is I don't play a lot of games, but the games I do play I really like, so I want to have them alongside my Virtual Console games.

This is just my personal taste, but if someone shares a similar vision to mine they can start here.

I am not updating the source, I try to watch the retroarch project as it progresses and it hasn't had any new features for Wii. And I ran into various issues trying to use one of the cores, this is one of the many reasons why I don't like the latest version, there's too many issues with no clue about fixing them.

All I need from RA is working just fine with this source(based 1.0.0.2), I've merged some changes from upstream; more recently the 240p fix, but RA is quite different now so I can't merge everything, for example the hid controller support.

On github this isn't treated as a fork because I didn't fork it, so I can't merge with them and even if I could the sources are very different now it probably wouldn't work. That's what you're asking, right?

**Comment by GeitHub** [comment]
Yep, you answered all my questions and it sounds like this project would be well-suited for the softmod project I'm working on & so now I have some follow ups. I checked your other project & noticed that you have a few custom cores & I'm assuming they offer some improvement & was wondering if they work with this modified version? Besides that I'm just fuzzy about compiling this together. RA's Github mentions devkitpro & something about a library? But I don't have a library card. Kidding, but seriously I have 0 experience with it so if you already have a pre-compiled zip on your computer that you could send my way I'd appreciate it, otherwise I'm sure I can probably figure it out.

Thanks again.

**Comment by SuperrSonic** [comment]
https://www.dropbox.com/s/euuqz9m0hebewpo/RA_backup.zip?dl=1

That's the only pack I have available, it's just a backup of the sources for regular RA and the stripped version, see the single game loading folder for builds and some examples.

All you need to compile it is devkitppc and libogc, download a core's source, do "make -f makefile.libretro platform=wii" copy the .a file to the retroarch source root and rename to "libretro_wii.a" Then do "make -f makefile.griffin platform=wii".

This is the forwarder I use for my channels: [forwarder-with-meta.xml-support](https://gbatemp.net/threads/forwarder-with-meta-xml-support.273165/)
I compile it each time so it looks for sd:/apps/retroarch/forwarders/meta*.xml
The * being an ID or the name of the game so I can tell it apart from the others.
The meta.xml simply holds two arguments one for the path to the game and the actual file name.

It's a tad convoluted, but once it's setup all I have to do is click start and play away.

![img_20160407_124233](https://cloud.githubusercontent.com/assets/6880539/15104810/2dba7020-158a-11e6-883c-92b0f3119156.jpg)
