### ISSUE TITLE
Save slot

### ISSUE THREAD

**Issue by baco81** [SuperrSonic/RA-SS#13]
Hi Superrsonic!
This is not an issue but more of a request. I usually save to several slots, not just one. The problem is that the option to change the save slot is not in the main game menu, so I have to navigate through the sub settings every time I want to change it. That's not very convenient.
Could this option be placed into the main game menu? Maybe with an option to hide it as there is for taking screenshots...

Thank you in advance.

Regards.

**Comment by SuperrSonic** [comment]
I can see that being useful, I'll probably leave the original setting as is and just copy it to the main menu, along with a hide setting. Default will be off.

Slot amount is fine, right? I don't think more than 10 is necessary since they're not even identified. This is why I rather just use slot 0 for "suspending" with the auto settings and slot 1 for regular state loading.

**Comment by baco81** [comment]
Yeah! I think that 10 slots are fine. I usually use 4 or 5 of them, but is good to have a little bit more just in case, so I think 10 is alright.

Thank you!

**Comment by SuperrSonic** [comment]
It's done.

**Comment by baco81** [comment]
Finally I had some time to download and try the update. Nice work. Thank you very much!
