### ISSUE TITLE
Buttons not working in beetle supergrafx

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#17]
Run won't work to start the game even though it's assigned in the menu so I think it's not registering any buttons presses. Thanks

**Comment by SuperrSonic** [comment]
I know this issue, it's present on the more accurate pce core. The problem is in update_input, where it does some checks for turbo settings that fail at start but can be forced by going into Settings->Input, etc.

Solution I've decided on is to remove those settings to get input working at start, if you want a better fix tell the core maintainers instead.

**Comment by filevans** [comment]
That seems good enough thanks
