### ISSUE TITLE
"QuickNes" error 

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#21]
O núcleo quicknes esta travando quando troca de jogo!

**Comment by SuperrSonic** [comment]
I've been tracing it back to 2015 commits and it still happens.
I've updated the core anyway, since it now includes palette options, I threw in the missing nintendo palettes (animal crossing, 3ds vc, restored wii vc).

I do have one way to fix it, I've been wanting to do it for other reasons. By replacing the "Load Content" function with something that reloads the core first. I want to see if I can make this happen because of the limited number of game loads. It would make the loading time a bit slower.

**Comment by rogerioronin** [comment]
Obrigado pela resposta, seria uma solução muito inteligente implementar o carregamento do core antes de carregar o jogo, realmente resolveria o problema do core QuickNES e do limite de carregamento por core!
Outro problema que eu percebi é que esta versão do RetroArch sua, aparentemente não oferecer suporte a WiiFlow (Lite) por SD e USB, seria interessante implementar esta função, muitas pessoas usam o WiiFlow (Lite) ! 
Obrigado pelo trabalho excelente que esta tornando esta sua versão uma "obra de arte" para o nosso velho Nintendo Wii!  
    Em domingo, 21 de julho de 2019 01:41:54 BRT, Diego A. <notifications@github.com> escreveu:  
 
 
Closed #21.

**Comment by SuperrSonic** [comment]
Can you post an .ini of the plugin?

**Comment by rogerioronin** [comment]
plugin do FBA neogeo


[PLUGIN]
displayname=FBA Neo
magic=464E454F
coverfolder=retroarch
dolfile=Retroarch/fba_neogeo.dol
romdir=jogos/NeoGeo/NeoGeo
filetypes=.zip
consolecoverid=
covercolor=ffffff
bannersound=Musicas/NeoGeo.ogg
arguments={device}:/{path}/|{name}


não funciona
