### ISSUE TITLE
Wonderswan & Virtual Boy Cores performance issues, and a request/question.

### ISSUE THREAD

**Issue by Maesejesus** [SuperrSonic/RA-SS#33]
Hi SuperrSonic, I apologize for bothering you again, but I wanted to ask you a few things.

I haven't tried much the Mednafen Wonderswan core of your version of Retro Arch much in the past, but I've tried recently and I saw it has some weird stuttering issue... But apparently only with sound. 

I tried some 60 FPS games to see how they work and seemingly they run at the correct speed, but the sound stutters constantly. I've tried several versions of your fork as far as 2018 and seems like they were always like this. The (I think unofficial) cores floating around for old versions of Retro Arch and they don't suffer from this. Is this issue something possible to fix?

The Virtual Boy core also shows some serious performance issues, but on a general level. I tried several versions of your fork and all suffer from this, but also do the 1.0.02 versions of this core that I could try before writing this. I could swear I was able to play Virtual Boy on Retro Arch well at one point, but I just can not remember when of it is true. 

I know the Mednafen Wii VB emulator worked fine, at least. I imagine this will be a tougher thing to fix compared to the Wonderswan core. 

The last thing I wanted to mention is question/request. I saw in one of the later updates you added a Screen Width and Correction Amount. Screen Width works well, and it is pretty useful, but Correction Amount seemingly does nothing. Is it supposed to be a "horizontal" version of Screen Width? 

If not, could a "Screen Height" be implemented like the Screen Width? 

Beyond that I have nothing but good things to say about your version of Retro Arch, really. Now that I got an OSSC I've been re-configuring stuff (it's impressive how upscaled 240P looks coming from the Wii, and RA-SS makes old games look awesome!). 

I hope you have a good year!

**Comment by SuperrSonic** [comment]
VB is slow, if there's a build that isn't I can include it but right now there's nothing I can do.

Wonderswan games are around 70 fps, vsync will slow it down to 60 fps and cause the audio to stutter. Try setting vsync off.
This happens automatically in normal RA, I removed it to make sure games from other cores were not misbehaving by reporting slightly higher than 59.94 fps and skipping vsync.

I recently upgraded to an HDTV and found the widescreen support in RA to be very bad. Screen Width controls the VI scaler, in normal RA this is always scaling unless the framebuffer width and VI is 640, but now this setting lets you disable scaling in any framebuffer size, for example Screen Width 512 and resolution 512x480 on NES/SNES games results in a very sharp image that's near aspect-perfect, this is how widescreen correction is done in Mario All-Stars Wii/Brawl demos.

Correction Amount is a copy of Screen Width that solves a small issue. It does nothing unless you have Auto-Switch Res and Widescreen Correction enabled. It's a shortcut because the VI scaler has multiple uses.

There is no height equivalent that I can add, best quality is bilinear with a 2x filter or the 'prescale' option.

**Comment by Maesejesus** [comment]
I'll check other VB versions but I may have remembered wrong; in any case don't worry about it. 

I tried disabling the Vsync option on the WS core and that did fix the audio. I had no idea the normal Retro Arch disabled it (I still have lots to learn it seems!). Thank you, now I don't need to keep the old 1.0.0.2 version I had on my SD.

I'm with you, the Screen width option to make the picture to 512 does make it a lot sharper and nice (although I need to get used to it after spending years with the wider 640 view) that's why asked if there could be something on the vertical side (I do not know too much about these specific matters, sorry if it was a dumb question), and as I said, upscaled through the OSSC makes games look like never before. 

I just asked because I felt pixels felt slightly taller than wide. But I was using 448/224 Screen resolution, after reading your message I changed to 240/480 (and then doing custom ratio to 224) and that improved it quite a lot, things like circles do actually look like circles now, I changed all my settings for home consoles to use 240 now. Thank you! Now I only have to figure which Screen Resolution would be best for Game Boy and other portable machines.

I did not know much about the Widescreen used by Retro Arch, although I would not be surprised if it's bad because after all the Wii uses Anamorphic Widescreen, which is... Not very good. I do not like the stretching Anamorphic Widescreen does on 2D elements (specially text) so I've been using my Wii on 4:3 for years, unless I'm forced too (for some games).

Thank you for your time and your work, and sorry to bother you.
