### ISSUE TITLE
Game Cube controller

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#8]
Is this version of RetroArch not compatible with Game Cube control?

**Comment by SuperrSonic** [comment]
It is, it's unfortunately a bit more confusing to setup. It was the fastest way to fix the issue where you have to disconnect (or have disconnected) the wiimote before RA will read the GC controller.

To keep it short I ended up hacking in more pad code so that the GC controller acts like a wiimote, the user needs to edit the .cfg that corresponds to their cores, they have to replace most mappings to Wii buttons. And they should also disable "autodetect controllers", this will only cause problems.

Later on I can post some .cfg examples and try to explain it better. The end result is that it's setup like in VC, where player 1 can be both wiimote and GC port 1. Whereas in the official RA you can only use one at a time, and changing control scheme always resets mapping.

**Comment by SuperrSonic** [comment]
Here's an example with Gambatte:

First off set this to false
**input_autodetect_enable** = "**false**"

Then look for this:
**input_device_p1** = "**0**"  //Actual device, normally this would be wiimote, but now it's both
**input_player1_joypad_index** = "**0**" //controller port, 0=port number 1, up to 16=port 15
**input_libretro_device_p1** = "**0**" //RA device type, leave as is, 2=RetroPad w/ Analog, 1=RetroPad, 0=None
**input_player1_analog_dpad_mode** = "**1**" //use left analog stick to mirror dpad

*You may try using RGUI to change these settings but the possibility of locking yourself out is there.
Plus the way it handles device changing and joypad index seems to be lumped into one thing.
Not sure how that works, so it might be better to just edit the .cfg files elsewhere.

Let's say you want to enable GC port 2 to be able to play multiplayer:
input_device_p2 = "0" // picks out both wiimote and gc controller (RGUI will say GC)
input_player2_joypad_index = "1" //uses port 2
input_libretro_device_p2 = "0" //will read as None in RGUI, I don't think it matters
input_player2_analog_dpad_mode = "1" //enable analog stick as dpad.

And now for the mappings:

**input_player1_up_btn** = "**50**"
This is the UP button, for wiimote [the value is 50](https://github.com/SuperrSonic/RA-SS/blob/master/input/gx_input_joypad.c#L88), (for GC it's 8 but that no longer matters) the GC UP will automatically work as well. Once it's all done you should never have to go in and change anything.
So just do this for the rest of the buttons and for the missing wiimote buttons just use GC buttons.

Some cores have specific mappings to improve things, for example SNES cores that end with "_direct" have direct mapping, while the "_alt" cores have a mapping that lets you play Super Mario World with the wiimote. What happens here is that if you map something so that it works better in certain games, the RGUI controls are _also_ affected. Once again out of necessity I worked around this by including two cores so that one has the RGUI mappings switched around; there's a text file that explains it in the package and also includes the mapping info.

Additionally since I removed the menu combo for GC, you can add:
**input_menu_toggle_axis** = "+2"
to make the C stick let you call the menu, where +2 means it's C stick to the right.

I've uploaded my own cfg (renamed txt so that it uploads here) which is already setup.
[gambatte.dol.cfg.txt](https://github.com/SuperrSonic/RA-SS/files/2330974/gambatte.dol.cfg.txt)

**Comment by rogerioronin** [comment]
how do you upload the "cfg" of the CPS1 core, please

**Comment by rogerioronin** [comment]
I do not understand much, would not you like to upload all the "cfg" files that are inside the "retroarch" folder?

It would help a lot!

**Comment by SuperrSonic** [comment]
I have a plan to fix the remapping issues as best as I can, but it will take some time to test. And getting all the cores compiled again will take some time and patience.

**Comment by rogerioronin** [comment]
Thanks for working on the problem, if you want help testing, I will do my best to be helpful!
